### ISSUE TITLE
Error returned to consumer should derive Fail

### ISSUE THREAD

**Issue by D4nte** [coblox/jsonrpc-rust-client#15]
As we (CoBloX) are aiming to use failure::Error more widely I suggest we provide a conversion to `failure::Error` for the errors provided by this crate.

**Comment by D4nte** [comment]
One of the benefit would be to use `?` instead of `unwrap()` in integration tests.

**Comment by thomaseizinger** [comment]
I think the way to go for libraries is to just derive `Fail`.

**Comment by D4nte** [comment]
Deprecated due to coblox/bitcoinrpc-rust-client#44 as we are going to deprecate this entire repo
